version: '3'
services:
  staging-web:
    image: cdtaylormesec/cacticultures-site:latest
    ports:
      - "8002:80"
    volumes:
      - ./nginx.staging.conf:/etc/nginx/conf.d/default.conf
      - ./staging:/usr/share/nginx/html
    environment:
      - NODE_ENV=staging
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: unless-stopped
